// <auto-generated />
using System;
using MPK.Connect.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MPK.Connect.DataAccess.Migrations
{
    [DbContext(typeof(MpkContext))]
    [Migration("20180618195355_ModelsAdded")]
    partial class ModelsAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MPK.Connect.Model.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Language");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Phone");

                    b.Property<string>("Timezone")
                        .IsRequired();

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("MPK.Connect.Model.Calendar", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("Friday");

                    b.Property<bool>("Monday");

                    b.Property<bool>("Saturday");

                    b.Property<DateTime>("StartDate");

                    b.Property<bool>("Sunday");

                    b.Property<bool>("Thursday");

                    b.Property<bool>("Tuesday");

                    b.Property<bool>("Wednesday");

                    b.HasKey("ServiceId");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("MPK.Connect.Model.CalendarDate", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("ExceptionRule");

                    b.HasKey("ServiceId");

                    b.ToTable("CalendarDates");
                });

            modelBuilder.Entity("MPK.Connect.Model.ControlStop", b =>
                {
                    b.Property<int>("StopId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("StopId1");

                    b.Property<int>("VariantId");

                    b.HasKey("StopId");

                    b.HasIndex("StopId1");

                    b.HasIndex("VariantId");

                    b.ToTable("ControlStop");
                });

            modelBuilder.Entity("MPK.Connect.Model.FeedInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Language");

                    b.Property<string>("PublisherName");

                    b.Property<string>("PublisherUrl");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("FeedInfos");
                });

            modelBuilder.Entity("MPK.Connect.Model.Route", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AgencyId");

                    b.Property<string>("Description");

                    b.Property<string>("LongName");

                    b.Property<int>("RouteTypeId");

                    b.Property<string>("ShortName");

                    b.Property<int?>("StopId");

                    b.Property<int>("StopTypeId");

                    b.Property<DateTime>("ValidFrom");

                    b.Property<DateTime>("ValidUntil");

                    b.Property<int>("VehicleType");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("RouteTypeId");

                    b.HasIndex("StopId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("MPK.Connect.Model.RouteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("RouteType");
                });

            modelBuilder.Entity("MPK.Connect.Model.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<int>("Sequence");

                    b.HasKey("Id");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("MPK.Connect.Model.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("MPK.Connect.Model.StopTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ArrivalTime");

                    b.Property<DateTime>("DepartureTime");

                    b.Property<int>("DropOffType");

                    b.Property<int>("PickupType");

                    b.Property<int>("StopId");

                    b.Property<int>("StopSequence");

                    b.Property<int>("TripId");

                    b.Property<string>("TripId1");

                    b.HasKey("Id");

                    b.HasIndex("StopId");

                    b.HasIndex("TripId1");

                    b.ToTable("StopTime");
                });

            modelBuilder.Entity("MPK.Connect.Model.Trip", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BrigadeId");

                    b.Property<int>("DirectionId");

                    b.Property<string>("HeadSign");

                    b.Property<int>("RouteId");

                    b.Property<string>("RouteId1");

                    b.Property<int>("ServiceId");

                    b.Property<int>("ShapeId");

                    b.Property<int>("VariantId");

                    b.Property<int>("VehicleId");

                    b.HasKey("Id");

                    b.HasIndex("RouteId1");

                    b.HasIndex("ServiceId");

                    b.HasIndex("ShapeId");

                    b.HasIndex("VariantId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("MPK.Connect.Model.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisjoinStopId");

                    b.Property<int>("EquivalentMainVariantId");

                    b.Property<bool>("IsMain");

                    b.Property<int>("JoinStopId");

                    b.HasKey("Id");

                    b.HasIndex("DisjoinStopId");

                    b.HasIndex("JoinStopId");

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("MPK.Connect.Model.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Description");

                    b.Property<int>("Name");

                    b.Property<int>("Symbol");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("MPK.Connect.Model.ControlStop", b =>
                {
                    b.HasOne("MPK.Connect.Model.Stop", "Stop")
                        .WithMany()
                        .HasForeignKey("StopId1");

                    b.HasOne("MPK.Connect.Model.Variant", "Variant")
                        .WithMany("ControlStops")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MPK.Connect.Model.Route", b =>
                {
                    b.HasOne("MPK.Connect.Model.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MPK.Connect.Model.RouteType", "RouteType")
                        .WithMany()
                        .HasForeignKey("RouteTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MPK.Connect.Model.Stop")
                        .WithMany("Routes")
                        .HasForeignKey("StopId");
                });

            modelBuilder.Entity("MPK.Connect.Model.StopTime", b =>
                {
                    b.HasOne("MPK.Connect.Model.Stop", "Stop")
                        .WithMany("StopTimes")
                        .HasForeignKey("StopId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MPK.Connect.Model.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId1");
                });

            modelBuilder.Entity("MPK.Connect.Model.Trip", b =>
                {
                    b.HasOne("MPK.Connect.Model.Route", "Route")
                        .WithMany("Trips")
                        .HasForeignKey("RouteId1");

                    b.HasOne("MPK.Connect.Model.Calendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MPK.Connect.Model.CalendarDate", "CalendarDate")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MPK.Connect.Model.Shape", "Shape")
                        .WithMany()
                        .HasForeignKey("ShapeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MPK.Connect.Model.Variant", "Variant")
                        .WithMany("Trips")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MPK.Connect.Model.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MPK.Connect.Model.Variant", b =>
                {
                    b.HasOne("MPK.Connect.Model.Stop", "DisjoinStop")
                        .WithMany("DisjoinVariants")
                        .HasForeignKey("DisjoinStopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MPK.Connect.Model.Stop", "JoinStop")
                        .WithMany("JoinVariants")
                        .HasForeignKey("JoinStopId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
