// <auto-generated />
using System;
using MPK.Connect.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MPK.Connect.DataAccess.Migrations
{
    [DbContext(typeof(MpkContext))]
    [Migration("20181013164746_Generic")]
    partial class Generic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MPK.Connect.Model.Agency", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FareUrl");

                    b.Property<string>("Id");

                    b.Property<string>("Language");

                    b.Property<string>("Phone");

                    b.Property<string>("Timezone")
                        .IsRequired();

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("Name");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("MPK.Connect.Model.Calendar", b =>
                {
                    b.Property<string>("ServiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDate");

                    b.Property<bool>("Friday");

                    b.Property<bool>("Monday");

                    b.Property<bool>("Saturday");

                    b.Property<DateTime>("StartDate");

                    b.Property<bool>("Sunday");

                    b.Property<bool>("Thursday");

                    b.Property<bool>("Tuesday");

                    b.Property<bool>("Wednesday");

                    b.HasKey("ServiceId");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("MPK.Connect.Model.CalendarDate", b =>
                {
                    b.Property<string>("ServiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("ExceptionRule");

                    b.HasKey("ServiceId");

                    b.ToTable("CalendarDates");
                });

            modelBuilder.Entity("MPK.Connect.Model.FeedInfo", b =>
                {
                    b.Property<string>("PublisherName")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Language")
                        .IsRequired();

                    b.Property<string>("PublisherUrl")
                        .IsRequired();

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("Version");

                    b.HasKey("PublisherName");

                    b.ToTable("FeedInfos");
                });

            modelBuilder.Entity("MPK.Connect.Model.Route", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AgencyId");

                    b.Property<string>("Color");

                    b.Property<string>("Description");

                    b.Property<string>("LongName")
                        .IsRequired();

                    b.Property<string>("ShortName")
                        .IsRequired();

                    b.Property<string>("SortOrder");

                    b.Property<string>("TextColor");

                    b.Property<int>("Type");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("MPK.Connect.Model.Shape", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("DistTraveled");

                    b.Property<string>("PointLatitude")
                        .IsRequired();

                    b.Property<string>("PointLongitude")
                        .IsRequired();

                    b.Property<int>("PointSequence");

                    b.HasKey("Id");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("MPK.Connect.Model.Stop", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<string>("Description");

                    b.Property<double>("Latitude");

                    b.Property<int>("LocationType");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("ParentStation");

                    b.Property<string>("Timezone");

                    b.Property<string>("Url");

                    b.Property<int>("WheelchairBording");

                    b.Property<string>("ZoneId");

                    b.HasKey("Id");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("MPK.Connect.Model.Trip", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlockId");

                    b.Property<int>("DirectionId");

                    b.Property<string>("HeadSign");

                    b.Property<string>("RouteId")
                        .IsRequired();

                    b.Property<string>("ServiceId")
                        .IsRequired();

                    b.Property<string>("ShapeId");

                    b.Property<string>("ShortName");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("ShapeId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("MPK.Connect.Model.Trip", b =>
                {
                    b.HasOne("MPK.Connect.Model.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MPK.Connect.Model.Shape", "Shape")
                        .WithMany()
                        .HasForeignKey("ShapeId");
                });
#pragma warning restore 612, 618
        }
    }
}
