// <auto-generated />
using System;
using MPK.Connect.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MPK.Connect.DataAccess.Migrations
{
    [DbContext(typeof(MpkContext))]
    partial class MpkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MPK.Connect.Model.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Language");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Timezone");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("MPK.Connect.Model.ControlStop", b =>
                {
                    b.Property<int>("StopId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("StopId1");

                    b.Property<int>("VariantId");

                    b.HasKey("StopId");

                    b.HasIndex("StopId1");

                    b.HasIndex("VariantId");

                    b.ToTable("ControlStops");
                });

            modelBuilder.Entity("MPK.Connect.Model.Route", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AgencyId");

                    b.Property<string>("Description");

                    b.Property<string>("LongName");

                    b.Property<int>("RouteTypeId");

                    b.Property<string>("ShortName");

                    b.Property<int>("StopTypeId");

                    b.Property<string>("StopTypeId1");

                    b.Property<DateTime>("ValidFrom");

                    b.Property<DateTime>("ValidUntil");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.HasIndex("RouteTypeId");

                    b.HasIndex("StopTypeId1");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("MPK.Connect.Model.RouteType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("RouteTypes");
                });

            modelBuilder.Entity("MPK.Connect.Model.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<int>("Sequence");

                    b.HasKey("Id");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("MPK.Connect.Model.Stop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Latitude");

                    b.Property<string>("Longitude");

                    b.Property<string>("Name");

                    b.Property<int>("StopTypeId");

                    b.Property<string>("StopTypeId1");

                    b.HasKey("Id");

                    b.HasIndex("StopTypeId1");

                    b.ToTable("Stops");
                });

            modelBuilder.Entity("MPK.Connect.Model.StopType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("StopTypes");
                });

            modelBuilder.Entity("MPK.Connect.Model.Trip", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BrigadeId");

                    b.Property<int>("DirectionId");

                    b.Property<string>("HeadSign");

                    b.Property<int>("RouteId");

                    b.Property<string>("RouteId1");

                    b.Property<int>("ServiceId");

                    b.Property<int>("ShapeId");

                    b.Property<int>("VariantId");

                    b.Property<int>("VehicleId");

                    b.HasKey("Id");

                    b.HasIndex("RouteId1");

                    b.HasIndex("ShapeId");

                    b.HasIndex("VariantId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("MPK.Connect.Model.Variant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisjoinStopId");

                    b.Property<int>("EquivalentMainVariantId");

                    b.Property<bool>("IsMain");

                    b.Property<int>("JoinStopId");

                    b.HasKey("Id");

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("MPK.Connect.Model.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Description");

                    b.Property<int>("Name");

                    b.Property<int>("Symbol");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("MPK.Connect.Model.ControlStop", b =>
                {
                    b.HasOne("MPK.Connect.Model.Stop", "Stop")
                        .WithMany()
                        .HasForeignKey("StopId1");

                    b.HasOne("MPK.Connect.Model.Variant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MPK.Connect.Model.Route", b =>
                {
                    b.HasOne("MPK.Connect.Model.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MPK.Connect.Model.RouteType", "RouteType")
                        .WithMany()
                        .HasForeignKey("RouteTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MPK.Connect.Model.StopType", "StopType")
                        .WithMany()
                        .HasForeignKey("StopTypeId1");
                });

            modelBuilder.Entity("MPK.Connect.Model.Stop", b =>
                {
                    b.HasOne("MPK.Connect.Model.StopType", "StopType")
                        .WithMany("Stops")
                        .HasForeignKey("StopTypeId1");
                });

            modelBuilder.Entity("MPK.Connect.Model.Trip", b =>
                {
                    b.HasOne("MPK.Connect.Model.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId1");

                    b.HasOne("MPK.Connect.Model.Shape", "Shape")
                        .WithMany()
                        .HasForeignKey("ShapeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MPK.Connect.Model.Variant", "Variant")
                        .WithMany()
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MPK.Connect.Model.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
